### ISSUE TITLE
Upgrade to Ubuntu 16.04

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/docker-ubuntu-base#14]
The new Ubuntu LTS is here and our base images are eager to receive updated software. There should be some heavy testing before making this change. A rapid thinking makes me think of some questions:
- Does it break the dependencies we install?
- Every package we use is included in this new release?
- Does Python 3.5 pose a threat to the operativeness of our 2.7-based software?
- Odoo runs well in it?

If anyone wants to post tests of this kind, feel free to comment below your experience. I will do some too.

**Comment by nhomar** [comment]
- Does it break the dependencies we install?

odoo-shippable-image is the place where test this.

- Every package we use is included in this new release?

odoo-shippable-image is the place where test this. (as this is the base, we must check is in the iamged based on this one).

- Does Python 3.5 pose a threat to the operativeness of our 2.7-based software?

I am actually using pure 2.7 soft in my personal 16.04 ubuntu, and it brings 2.7 by default, just 3.5 pre installed.

- Odoo runs well in it?

For me it is working but we must test this ins the specific images.

**Comment by ruiztulio** [comment]
@LuisAlejandro As this is the base image for the the [Odoo base images](https://github.com/Vauxoo/docker-odoo-image) and at the same time the shippable image is [based on odoo80](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo-shippable/Dockerfile#L1) image for a proper test we _could_ need to build the ubuntu base -> odoo80 -> shippable to do a proper test with Odoo, but you can execute the Odoo tests in odoo80 image (this adds some dependencies for the same odoo version) to check if everything is working fine.

But this test may imply that the odoo80/90/70 images will need to be tweaked to work with the new version.
