### ISSUE TITLE
Error building image

### ISSUE THREAD

**Issue by ruiztulio** [Vauxoo/docker-ubuntu-base#20]
@LuisAlejandro 

I'm getting the following error in hub.docker.com:
![error_hub](http://screenshots.vauxoo.com/tulio/10245314416-juisOSogKp.jpg)

I know it was working (I tested it locally) on Saturday. In my local I get the following error:
![error_local](http://screenshots.vauxoo.com/tulio/10285314416-ItvHwRDX92.jpg)

In the firsts lines you can see the Postgres certificate. Then I even installed wget just to test:
![install_wget](http://screenshots.vauxoo.com/tulio/10392114416-m30HsI12Wj.jpg)

but still get an error:
![error_wget](http://screenshots.vauxoo.com/tulio/10380714416-CKq9xMXWsV.jpg)

@moylop260 The locales won't be available until this image can be built in hub.docker 

Regards

**Comment by moylop260** [comment]
@LuisAlejandro 
I don't understand why we have this issues if the initial tests from https://github.com/Vauxoo/docker-ubuntu-base/pull/11#issuecomment-216876967 ran done!

**Comment by LuisAlejandro** [comment]
@moylop260 Checking!

**Comment by LuisAlejandro** [comment]
Removing the -q (--quiet) parameter to wget reveals that adding the gpg key from postgresql actually never worked and we couldn't see it because of the quiet and because we didn't have [set -e](https://github.com/Vauxoo/docker-ubuntu-base/pull/17/commits/b1f5c4a89ede48d14fc5c34799f26ce1292eef68#diff-d2ff34f73419a2f54edcc6a5fc1f020aR4), so the script continued if there was an error.

```
+ wget -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc
--2016-05-24 12:08:03--  https://www.postgresql.org/media/keys/ACCC4CF8.asc
Resolving www.postgresql.org (www.postgresql.org)... 217.196.149.50, 87.238.57.232, 174.143.35.230, ...
Connecting to www.postgresql.org (www.postgresql.org)|217.196.149.50|:443... connected.
ERROR: cannot verify www.postgresql.org's certificate, issued by ‘/C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2’:
  Unable to locally verify the issuer's authority.
To connect to www.postgresql.org insecurely, use `--no-check-certificate'.
```

The solution to this is to install the package ca-certificates before the key is added. Will make a PR ASAP.

**Comment by LuisAlejandro** [comment]
@moylop260 @ruiztulio PR is ready #21

**Comment by LuisAlejandro** [comment]
I also removed the custom download function, because now we install wget first.
https://github.com/Vauxoo/docker-ubuntu-base/pull/21/files#diff-5eee01526cae40785348322758638f44L5

**Comment by ruiztulio** [comment]
@moylop260 @LuisAlejandro The image was built in hub:
![build](http://screenshots.vauxoo.com/tulio/09494114516-GpFRZsrBJQ.jpg)

No errors, now I triggered the build of odoo80 one and the I'll do the same with the odoo shippable.

Regards

**Comment by ruiztulio** [comment]
@moylop260 finally the shippable image is done with no errors:
![shippable](http://screenshots.vauxoo.com/tulio/11020014516-tVin4lpyFK.jpg)

**Comment by moylop260** [comment]
Thanks
