### ISSUE TITLE
WARNING on runbot builds: Unable to get information for locale language.

### ISSUE THREAD

**Issue by dsabrinarg** [Vauxoo/docker-ubuntu-base#22]
We had this new warning on runbot:
WARNING openerp_test openerp.addons.base.res.res_lang: Unable to get information for locale es_MX. Information from the default locale (en_US) have been used.

Must be related to [this](https://github.com/Vauxoo/docker-ubuntu-base/blob/master/Dockerfile#L5) change.

**Comment by dsabrinarg** [comment]
@LuisAlejandro @moylop260 @ruiztulio we have this new issue on runbot.vauxoo.com

**Comment by moylop260** [comment]
Could you check it @LuisAlejandro?

**Comment by LuisAlejandro** [comment]
Sure.
It has to do with this https://github.com/Vauxoo/docker-ubuntu-base/blob/master/Dockerfile#L4
I'll add es_MX.

I wonder, do we use other locales to add them as well? Or should i add all of them?

Thanks for reporting.

**Comment by moylop260** [comment]
@ruiztulio could you give us your opinion of how to fix it?

**Comment by ruiztulio** [comment]
@moylop260 IMHO we should add them as we see them fit...so far (besides fr and us) mx, pa, ve and gt (I think)

**Comment by moylop260** [comment]
Ok
:+1:

**Comment by LuisAlejandro** [comment]
Cool. Then I'll add:

"es_MX.UTF-8" "es_PA.UTF-8" "es_VE.UTF-8" "es_GT.UTF-8"

**Comment by nhomar** [comment]
On Fri, Jun 3, 2016 at 6:06 PM, Luis Alejandro Martínez Faneyth <
notifications@github.com> wrote:

> "es_MX.UTF-8" "es_PA.UTF-8" "es_VE.UTF-8" "es_GT.UTF-8"


add es_PE also please


-- 
Nhomar Hernandez
CEO Vauxoo.
Site: http://vauxoo.com
Twitter: @nhomar
Blog: http://nhomar.com
Github User: https://github.com/nhomar
Odoo Gold Partner
Skype: nhomar00 (Envia mail previo no lo superviso siempre).
HangOut: nhomar@vauxoo.com
Móvil Venezuela:
+58 4144110269
Móvil México:
+52 1 4773933942

**Comment by LuisAlejandro** [comment]
Done!

**Comment by moylop260** [comment]
@dsabrinarg 
FYI now is green
<img width="509" alt="screen shot 2016-06-05 at 11 03 04 am" src="https://cloud.githubusercontent.com/assets/6644187/15806636/461d3b28-2b0d-11e6-8e85-cd758730147c.png">

**Comment by dsabrinarg** [comment]
Thanks @moylop260
