### ISSUE TITLE
workaround to avoid numpy weird errors

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-ubuntu-base#85]
Currently, if numpy is available in the modules even if you are not using it
Odoo try to compile and the system is down only for a type of processor

Currently we know 2 server reproducing the error:
 1) B&F-production
 2) Runbot

More info about:
 - https://github.com/numpy/numpy/issues/17674
 - https://github.com/numpy/numpy/pull/17759

It is reproducing in the following MR:
 - https://git.vauxoo.com/vauxoo/lasec/-/merge_requests/197

Check the following discussion https://odoo-community.org/groups/contributors-15/contributors-186006?mode=thread&date_begin=&date_end=

> 
OpenBLAS creates a number of threads equal to the number of core threads available: 56 in my case (production server),
so it quickly reached limit_memory_hard
and the process was killed (SIGSEGV)
Forcing OPENBLAS_NUM_THREADS=1 fixed the issue.

I just build a image to reproduce the error then I use that environment variable and it is fixed.

So, in order to avoid reproducing this issue in the future we need use it for all images as `ENV` in the Dockerfile

For all branches

**Comment by moylop260** [comment]
@ruiztulio @Angelfentanez agree?

**Comment by fernandahf** [comment]
For record, this error was solved in:

- https://github.com/Vauxoo/docker-ubuntu-base/pull/89
- https://github.com/Vauxoo/docker-ubuntu-base/pull/90

I will close this issue.
